[package]
name = "mogh_encryption"
description = "Utilities to encrypt and decrypt data."
version = "2.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chacha20poly1305.workspace = true
aes-gcm.workspace = true
# Only to enable the 'zeroize' features (see workspace Cargo.toml).
chacha20.workspace = true
aes.workspace = true
ghash.workspace = true
polyval.workspace = true
data-encoding.workspace = true
anyhow.workspace = true
rand.workspace = true
zeroize.workspace = true
subtle.workspace = true
