[install-auth-client]
alias = "iac"
description = "Installs the auth ts client dependencies"
cmd = "cd ./auth/client/ts && npm install"

[gen-auth-client]
alias = "gac"
description = "Generates auth typescript types and build the auth ts client"
after = "install-auth-client"
cmd = """
node ./auth/client/ts/generate_types.mjs && \
cd ./auth/client/ts && npm run build"""
