/*
 Generated by typeshare 1.13.4
*/

/** Represents an empty json object: `{}` */
export interface NoData {
}

export type BeginExternalLoginLinkResponse = NoData;

export type CreationChallengeResponse = any;

/** Response for [BeginPasskeyEnrollment]. */
export type BeginPasskeyEnrollmentResponse = CreationChallengeResponse;

/** JSON containing a jwt authentication token. */
export interface JwtResponse {
	/** A token the user can use to authenticate their requests. */
	jwt: string;
}

/** Response for [CompletePasskeyLogin]. */
export type CompletePasskeyLoginResponse = JwtResponse;

/** Response for [CompleteTotpLogin]. */
export type CompleteTotpLoginResponse = JwtResponse;

/** Response for [CompleteTotpRecoveryLogin]. */
export type CompleteTotpRecoveryLoginResponse = JwtResponse;

/** Response for [ConfirmPasskeyEnrollment]. */
export type ConfirmPasskeyEnrollmentResponse = NoData;

/** The kind specific configuration of an [ExternalLoginProvider]. */
export type ExternalLoginProviderConfig = 
	| { kind: "Oidc", params: OidcConfig }
	| { kind: "Github", params: NamedOauthConfig }
	| { kind: "Google", params: NamedOauthConfig };

/**
 * An external login provider users can log in with.
 * Any number of these can be configured, either statically
 * by the app (file / env) or stored by the app and managed over the API.
 */
export interface ExternalLoginProvider {
	/**
	 * The unique id of the provider. Part of the login / callback urls,
	 * and stored alongside the external user id on linked users.
	 * 
	 * External user ids are only unique per provider,
	 * so an id must never be reused for another provider.
	 */
	id: string;
	/** The display name, eg. shown on the login button. */
	name: string;
	/** Disable new user registration using this provider. */
	registration_disabled?: boolean;
	/** The kind specific provider configuration. */
	config: ExternalLoginProviderConfig;
}

/** An external login provider as listed for admins. */
export interface ExternalLoginProviderListItem {
	/** The provider. The client secret is redacted. */
	provider: ExternalLoginProvider;
	/**
	 * Whether the provider comes from static app configuration
	 * (file / env), in which case it cannot be updated or deleted.
	 */
	read_only: boolean;
	/**
	 * The redirect / callback URI which
	 * must be registered at the provider.
	 */
	redirect_uri: string;
}

export type CreateExternalLoginProviderResponse = ExternalLoginProviderListItem;

/** Response for [DeleteApiKey]. */
export type DeleteApiKeyResponse = NoData;

/** Response for [DeleteApiKeyV2]. */
export type DeleteApiKeyV2Response = NoData;

export type DeleteExternalLoginProviderResponse = NoData;

/** Response for [ExchangeForJwt]. */
export type ExchangeForJwtResponse = JwtResponse;

export type JsonValue = any;

export type ListExternalLoginProvidersResponse = ExternalLoginProviderListItem[];

/** JSON containing either an authentication token or the required 2fa auth check. */
export type JwtOrTwoFactor = 
	| { type: "Jwt", data: JwtResponse }
	| { type: "Passkey", data: RequestChallengeResponse }
	| { type: "Totp", data: {
}};

/** The response for [LoginLocalUser] */
export type LoginLocalUserResponse = JwtOrTwoFactor;

export type Passkey = any;

export type PublicKeyCredential = any;

export type RegisterPublicKeyCredential = any;

export type RequestChallengeResponse = any;

/** Response for [SignUpLocalUser]. */
export type SignUpLocalUserResponse = JwtResponse;

export type U64 = number;

/** Response for [UnenrollPasskey]. */
export type UnenrollPasskeyResponse = NoData;

/** Response for [UnenrollTotp]. */
export type UnenrollTotpResponse = NoData;

export type UnlinkExternalLoginResponse = NoData;

export type UnlinkLocalLoginResponse = NoData;

export type UpdateExternalLoginProviderResponse = ExternalLoginProviderListItem;

export type UpdateExternalSkip2faResponse = NoData;

export type UpdatePasswordResponse = NoData;

export type UpdateUsernameResponse = NoData;

/**
 * Begin linking flow for an external login. Response: [NoData].
 * 
 * First call this method when authenticated, then redirect the
 * user to `/auth/external/{provider_id}/link`, using a provider id
 * from [GetLoginOptions][crate::api::login::GetLoginOptions].
 */
export interface BeginExternalLoginLink {
}

/**
 * Begins enrollment flow for Passkey 2FA.
 * Response: [BeginPasskeyEnrollmentResponse]
 */
export interface BeginPasskeyEnrollment {
}

/**
 * Starts enrollment flow for TOTP 2FA auth support.
 * Response: [BeginTotpEnrollmentResponse]
 * 
 * This generates an otpauth URI for the user. User must confirm
 * by providing a valid 6 digit code for the URI to [ConfirmTotpEnrollment].
 */
export interface BeginTotpEnrollment {
}

/** Response for [BeginTotpEnrollment]. */
export interface BeginTotpEnrollmentResponse {
	/** TOTP enrollment URI for manual addition to password manager. */
	uri: string;
	/** Base64 encoded PNG embeddable in HTML to display uri QR code. */
	png: string;
}

/**
 * Complete login using passkey as second factor.
 * Response: [CompletePasskeyLoginResponse].
 */
export interface CompletePasskeyLogin {
	credential: PublicKeyCredential;
}

/**
 * Complete login using TOTP code as second factor.
 * Response: [CompleteTotpLoginResponse].
 */
export interface CompleteTotpLogin {
	/** The time dependent totp code for user. */
	code: string;
}

/**
 * Complete login using a TOTP recovery code as second factor.
 * Each recovery code can only be used once.
 * Response: [CompleteTotpRecoveryLoginResponse].
 */
export interface CompleteTotpRecoveryLogin {
	/** One of the recovery codes issued at TOTP enrollment. */
	code: string;
}

/**
 * Confirm enrollment flow for Passkey 2FA.
 * Response: [NoData]
 */
export interface ConfirmPasskeyEnrollment {
	credential: RegisterPublicKeyCredential;
}

/**
 * Confirm enrollment flow for TOTP 2FA auth support
 * Response: [ConfirmTotpEnrollmentResponse]
 */
export interface ConfirmTotpEnrollment {
	code: string;
}

/** Response for [ConfirmTotpEnrollment]. */
export interface ConfirmTotpEnrollmentResponse {
	recovery_codes: string[];
}

/**
 * Create an API key for the calling user.
 * Response: [CreateApiKeyResponse].
 */
export interface CreateApiKey {
	/** The name for the api key. */
	name: string;
	/**
	 * A unix timestamp in millseconds specifying api key expire time.
	 * Default is 0, which means no expiry.
	 */
	expires?: U64;
	/**
	 * Whitelist of CIDR ranges (eg `10.0.0.0/8`) or ip addresses
	 * from which requests using this api key are accepted.
	 * Empty (the default) means all ips are allowed.
	 */
	cidr_whitelist?: string[];
}

/** Response for [CreateApiKey]. */
export interface CreateApiKeyResponse {
	/** X-API-KEY */
	key: string;
	/**
	 * X-API-SECRET
	 * 
	 * Note.
	 * There is no way to get the secret again after it is distributed in this response
	 */
	secret: string;
}

/**
 * Create an API key (v2) for the calling user.
 * Response: [CreateApiKeyV2Response].
 */
export interface CreateApiKeyV2 {
	/** The name for the api key. */
	name: string;
	/**
	 * A unix timestamp in millseconds specifying api key expire time.
	 * Default is 0, which means no expiry.
	 */
	expires?: U64;
	/**
	 * Whitelist of CIDR ranges (eg `10.0.0.0/8`) or ip addresses
	 * from which requests using this api key are accepted.
	 * Empty (the default) means all ips are allowed.
	 */
	cidr_whitelist?: string[];
	/**
	 * Optionally provide a pre-existing public key.
	 * Otherwise, a private key will be generated and
	 * returned in the response
	 */
	public_key?: string;
}

/** Response for [CreateApiKeyV2]. */
export interface CreateApiKeyV2Response {
	/**
	 * Used to sign requests for authentication
	 * without transmitting the key itself.
	 * 
	 * The server will store the associated public key.
	 * 
	 * If user provides a pre-existing public key,
	 * this field will be null.
	 */
	private_key?: string;
}

/**
 * Create an external login provider. Admin only.
 * The provider id is generated by the server.
 * Response: [ExternalLoginProviderListItem].
 */
export interface CreateExternalLoginProvider {
	/** The display name, eg. shown on the login button. */
	name: string;
	/** Disable new user registration using this provider. */
	registration_disabled?: boolean;
	/** The kind specific provider configuration. */
	config: ExternalLoginProviderConfig;
}

/**
 * Delete an API key for the calling user.
 * Response: [NoData].
 */
export interface DeleteApiKey {
	/** The key which the user intends to delete. */
	key: string;
}

/**
 * Delete an API key (v2) for the calling user.
 * Response: [NoData].
 */
export interface DeleteApiKeyV2 {
	/** The public key of the api key to delete. */
	public_key: string;
}

/**
 * Delete an external login provider. Admin only.
 * Users can no longer log in with the provider,
 * and their links to it are removed by the app.
 * Response: [NoData].
 */
export interface DeleteExternalLoginProvider {
	/** The id of the provider to delete. */
	id: string;
}

/**
 * Retrieve a JWT after completing third party login flows.
 * Response: [ExchangeForJwtResponse].
 */
export interface ExchangeForJwt {
}

/**
 * Get the available options to login, eg. local and external providers.
 * Response: [GetLoginOptionsResponse].
 */
export interface GetLoginOptions {
}

/** The kind of an external login provider. */
export enum ExternalLoginKind {
	Oidc = "Oidc",
	Github = "Github",
	Google = "Google",
}

/**
 * An enabled external login provider to show on the login page.
 * 
 * Login is started by redirecting the user to `/external/{id}/login`
 * relative to the auth api path, linking with `/external/{id}/link`.
 */
export interface LoginOptionsProvider {
	/** The provider id */
	id: string;
	/** The display name of the provider */
	name: string;
	/** The kind of provider, eg. to choose an icon. */
	kind: ExternalLoginKind;
	/** Whether new user registration is disabled for this provider */
	registration_disabled: boolean;
}

/** The response for [GetLoginOptions]. */
export interface GetLoginOptionsResponse {
	/** Whether Local login is enabled. */
	local: boolean;
	/** Whether local user registration (Sign Up) has been disabled */
	registration_disabled: boolean;
	/** The enabled external login providers. */
	providers: LoginOptionsProvider[];
	/**
	 * The id of the provider the login page should auto-redirect to
	 * instead of showing the login page, if any.
	 * This is the first enabled OIDC provider with `auto_redirect`.
	 */
	auto_redirect?: string;
}

/**
 * Get the calling user's ID.
 * Response: [GetUserIdResponse].
 */
export interface GetUserId {
}

export interface GetUserIdResponse {
	id: string;
}

/**
 * List all configured external login providers,
 * including disabled ones. Admin only.
 * Response: [ListExternalLoginProvidersResponse].
 */
export interface ListExternalLoginProviders {
}

/** Login as a local user. */
export interface LoginLocalUser {
	/** The user's username */
	username: string;
	/** The user's password */
	password: string;
}

/**
 * Configuration for a named Oauth2 provider,
 * like Github or Google.
 */
export interface NamedOauthConfig {
	/** Whether this login provider is enabled. */
	enabled?: boolean;
	/**
	 * The Oauth client id.
	 * 
	 * Alias: 'id'
	 */
	client_id?: string;
	/**
	 * The Oauth client secret.
	 * 
	 * Alias: 'secret'
	 */
	client_secret?: string;
}

/** Configuration for OIDC provider */
export interface OidcConfig {
	/** Enable login with configured OIDC provider. */
	enabled?: boolean;
	/**
	 * Configure OIDC provider address for
	 * communcation directly with the app server.
	 * 
	 * Note. Needs to be reachable from the app server.
	 * 
	 * `https://accounts.example.internal/application/o/appname`
	 */
	provider?: string;
	/**
	 * Configure OIDC user redirect host.
	 * 
	 * This is the host address users are redirected to in their browser,
	 * and may be different from the `provider` host.
	 * DO NOT include the `path` part, this must be inferred from the above provider path.
	 * If not provided, the host will be the same as `oidc_provider`.
	 * Eg. `https://accounts.example.external`
	 */
	redirect_host?: string;
	/**
	 * Set OIDC client id
	 * 
	 * Alias: 'id'
	 */
	client_id?: string;
	/**
	 * Set OIDC client secret
	 * 
	 * Alias: 'secret'
	 */
	client_secret?: string;
	/**
	 * Use the full email for usernames.
	 * Otherwise, the @address will be stripped,
	 * making usernames more concise.
	 */
	use_full_email?: boolean;
	/**
	 * Your OIDC provider may set additional audiences other than `client_id`,
	 * they must be added here to make claims verification work.
	 */
	additional_audiences?: string[];
	/**
	 * Automatically redirect unauthenticated users to the OIDC provider
	 * instead of showing the login page.
	 */
	auto_redirect?: boolean;
	/**
	 * Additional scopes to request from the provider,
	 * on top of `openid`, `profile` and `email`.
	 * 
	 * The `groups` scope is requested automatically when the
	 * `groups` claim is used and the provider advertises the scope
	 * (`scopes_supported`). Other scopes needed for the groups
	 * claim, eg. `roles`, must be added here.
	 */
	additional_scopes?: string[];
	/**
	 * The claim containing the groups the user belongs to, eg. `groups`.
	 * Nested claims can be reached with a dotted path,
	 * eg. `realm_access.roles`.
	 * 
	 * Group extraction is disabled if this is empty (default),
	 * unless `allowed_groups` or `admin_groups` are set,
	 * in which case it falls back to `groups`.
	 */
	groups_claim?: string;
	/**
	 * Only allow OIDC login, signup and account linking for
	 * users in at least one of these groups, or in `admin_groups`.
	 * Empty allows all users (default).
	 * 
	 * If the provider does not send any group information
	 * for the user, they are rejected.
	 */
	allowed_groups?: string[];
	/**
	 * Users in at least one of these groups are
	 * reported to the app as admins on OIDC login / signup.
	 * This can be used to onboard new admins through the provider.
	 */
	admin_groups?: string[];
}

/**
 * Sign up a new local user account.
 * Response: [SignUpLocalUserResponse].
 */
export interface SignUpLocalUser {
	/** The username for the new user. */
	username: string;
	/**
	 * The password for the new user.
	 * This cannot be retreived later.
	 */
	password: string;
}

/**
 * Unenrolls user in Passkey 2FA.
 * Response: [NoData]
 */
export interface UnenrollPasskey {
}

/**
 * Unenrolls user in TOTP 2FA.
 * Response: [UnenrollTotpResponse]
 */
export interface UnenrollTotp {
}

/**
 * Unlink an external login provider from the calling user.
 * Response: [NoData].
 */
export interface UnlinkExternalLogin {
	/** The id of the provider to unlink. */
	provider_id: string;
}

/**
 * Remove the password of the calling user,
 * disabling local login. Response: [NoData].
 */
export interface UnlinkLocalLogin {
}

/**
 * Update an external login provider, replacing its
 * name and configuration. Admin only.
 * Response: [ExternalLoginProviderListItem].
 * 
 * - The kind of the provider cannot be changed.
 * - If the client secret is empty or the redacted value from
 * [ListExternalLoginProviders], the existing secret is kept.
 * Pass `clear_client_secret` to remove it instead.
 */
export interface UpdateExternalLoginProvider {
	/** The id of the provider to update. */
	id: string;
	/** The display name, eg. shown on the login button. */
	name: string;
	/** Disable new user registration using this provider. */
	registration_disabled?: boolean;
	/** The kind specific provider configuration. */
	config: ExternalLoginProviderConfig;
	/**
	 * Remove the stored client secret, eg. to switch an OIDC
	 * provider to a public client using PKCE. An empty client
	 * secret on its own keeps the stored secret.
	 * 
	 * Cannot be combined with a new client secret.
	 */
	clear_client_secret?: boolean;
}

/**
 * Update whether the calling user skips 2fa when using external login method.
 * Response: [NoData].
 */
export interface UpdateExternalSkip2fa {
	/** Whether user skips 2fa when using external login method. */
	external_skip_2fa: boolean;
}

/**
 * Update the calling user's password.
 * Response: [NoData].
 */
export interface UpdatePassword {
	password: string;
}

/**
 * Update the calling user's username.
 * Response: [NoData].
 */
export interface UpdateUsername {
	username: string;
}

export type LoginRequest = 
	| { type: "GetLoginOptions", params: GetLoginOptions }
	| { type: "ExchangeForJwt", params: ExchangeForJwt }
	| { type: "SignUpLocalUser", params: SignUpLocalUser }
	| { type: "LoginLocalUser", params: LoginLocalUser }
	| { type: "CompletePasskeyLogin", params: CompletePasskeyLogin }
	| { type: "CompleteTotpLogin", params: CompleteTotpLogin }
	| { type: "CompleteTotpRecoveryLogin", params: CompleteTotpRecoveryLogin };

export type ManageRequest = 
	| { type: "GetUserId", params: GetUserId }
	| { type: "UpdateUsername", params: UpdateUsername }
	| { type: "UpdatePassword", params: UpdatePassword }
	| { type: "BeginExternalLoginLink", params: BeginExternalLoginLink }
	| { type: "UnlinkLocalLogin", params: UnlinkLocalLogin }
	| { type: "UnlinkExternalLogin", params: UnlinkExternalLogin }
	| { type: "ListExternalLoginProviders", params: ListExternalLoginProviders }
	| { type: "CreateExternalLoginProvider", params: CreateExternalLoginProvider }
	| { type: "UpdateExternalLoginProvider", params: UpdateExternalLoginProvider }
	| { type: "DeleteExternalLoginProvider", params: DeleteExternalLoginProvider }
	| { type: "BeginPasskeyEnrollment", params: BeginPasskeyEnrollment }
	| { type: "ConfirmPasskeyEnrollment", params: ConfirmPasskeyEnrollment }
	| { type: "UnenrollPasskey", params: UnenrollPasskey }
	| { type: "BeginTotpEnrollment", params: BeginTotpEnrollment }
	| { type: "ConfirmTotpEnrollment", params: ConfirmTotpEnrollment }
	| { type: "UnenrollTotp", params: UnenrollTotp }
	| { type: "UpdateExternalSkip2fa", params: UpdateExternalSkip2fa }
	| { type: "CreateApiKey", params: CreateApiKey }
	| { type: "DeleteApiKey", params: DeleteApiKey }
	| { type: "CreateApiKeyV2", params: CreateApiKeyV2 }
	| { type: "DeleteApiKeyV2", params: DeleteApiKeyV2 };

/** JSON containing either an authentication token or the required 2fa auth check. */
export type UserIdOrTwoFactor = 
	| { type: "UserId", data: string }
	| { type: "Passkey", data: RequestChallengeResponse }
	| { type: "Totp", data: {
}};

